'use strict';

const ROLLBACK_OPERATION_SCHEMA_VERSION = 1;

const ROLLBACK_OPERATION_TYPE = 'ROLLBACK';

const ROLLBACK_OPERATION_STATUS = Object.freeze({
    NOT_STARTED: 'NOT_STARTED',
    IN_PROGRESS: 'IN_PROGRESS',
    SUCCEEDED: 'SUCCEEDED',
    FAILED: 'FAILED',
    UNKNOWN_RESULT: 'UNKNOWN_RESULT'
});

const CHECK_ONLY_STATUS = Object.freeze({
    PENDING: 'PENDING',
    SUCCESS: 'SUCCESS',
    FAILED: 'FAILED'
});

const TERMINAL_ROLLBACK_OPERATION_STATUSES = Object.freeze([
    ROLLBACK_OPERATION_STATUS.SUCCEEDED,
    ROLLBACK_OPERATION_STATUS.FAILED,
    ROLLBACK_OPERATION_STATUS.UNKNOWN_RESULT
]);

const ALLOWED_TRANSITIONS = Object.freeze({
    [ROLLBACK_OPERATION_STATUS.NOT_STARTED]: [
        ROLLBACK_OPERATION_STATUS.IN_PROGRESS
    ],
    [ROLLBACK_OPERATION_STATUS.IN_PROGRESS]: [
        ROLLBACK_OPERATION_STATUS.SUCCEEDED,
        ROLLBACK_OPERATION_STATUS.FAILED,
        ROLLBACK_OPERATION_STATUS.UNKNOWN_RESULT
    ],
    [ROLLBACK_OPERATION_STATUS.UNKNOWN_RESULT]: [
        ROLLBACK_OPERATION_STATUS.SUCCEEDED,
        ROLLBACK_OPERATION_STATUS.FAILED
    ]
});

module.exports = {
    ROLLBACK_OPERATION_SCHEMA_VERSION,
    ROLLBACK_OPERATION_TYPE,
    ROLLBACK_OPERATION_STATUS,
    CHECK_ONLY_STATUS,
    TERMINAL_ROLLBACK_OPERATION_STATUSES,
    ALLOWED_TRANSITIONS
};
