'use strict';

const ACTOR_TRUST = Object.freeze({
    TRUSTED_ACTOR: 'TRUSTED_ACTOR',
    UNAUTHENTICATED: 'UNAUTHENTICATED',
    INVALID_ACTOR_CONTEXT: 'INVALID_ACTOR_CONTEXT'
});

const ROLLBACK_AUTHORIZATION_ACTION = Object.freeze({
    ROLLBACK: 'ROLLBACK',
    ROLLBACK_RECOVER: 'ROLLBACK_RECOVER',
    ROLLBACK_RECONCILE: 'ROLLBACK_RECONCILE'
});

const ROLLBACK_AUTHORIZATION_DECISION = Object.freeze({
    AUTHORIZED: 'AUTHORIZED',
    DENIED: 'DENIED',
    UNAVAILABLE: 'UNAVAILABLE'
});

const SALESFORCE_DEPLOY_STATUS = Object.freeze({
    SUCCEEDED: 'SUCCEEDED',
    FAILED: 'FAILED',
    IN_PROGRESS: 'IN_PROGRESS',
    NOT_FOUND: 'NOT_FOUND',
    UNKNOWN: 'UNKNOWN',
    UNAVAILABLE: 'UNAVAILABLE'
});

const AUTHORITATIVE_EVIDENCE_SOURCE = Object.freeze({
    SALESFORCE_DEPLOY_STATUS: 'SALESFORCE_DEPLOY_STATUS'
});

module.exports = {
    ACTOR_TRUST,
    ROLLBACK_AUTHORIZATION_ACTION,
    ROLLBACK_AUTHORIZATION_DECISION,
    SALESFORCE_DEPLOY_STATUS,
    AUTHORITATIVE_EVIDENCE_SOURCE
};
