'use strict';

const ROLLBACK_CODE = Object.freeze({
    DISABLED: 'ROLLBACK_DISABLED',
    SNAPSHOT_NOT_FOUND: 'ROLLBACK_SNAPSHOT_NOT_FOUND',
    SNAPSHOT_NOT_SEALED: 'ROLLBACK_SNAPSHOT_NOT_SEALED',
    SNAPSHOT_NOT_ELIGIBLE: 'ROLLBACK_SNAPSHOT_NOT_ELIGIBLE',
    STORAGE_UNAVAILABLE: 'ROLLBACK_STORAGE_UNAVAILABLE',
    INTEGRITY_MISMATCH: 'ROLLBACK_INTEGRITY_MISMATCH',
    ARTIFACT_MISSING: 'ROLLBACK_ARTIFACT_MISSING',
    ARTIFACT_HASH_MISMATCH: 'ROLLBACK_ARTIFACT_HASH_MISMATCH',
    IDENTITY_FAILURE: 'ROLLBACK_IDENTITY_FAILURE',
    DESTINATION_MISMATCH: 'ROLLBACK_DESTINATION_MISMATCH',
    UNSUPPORTED_METADATA: 'ROLLBACK_UNSUPPORTED_METADATA',
    NEW_MEMBER_PRESENT: 'ROLLBACK_NEW_MEMBER_PRESENT',
    MEMBER_NOT_MODIFIED: 'ROLLBACK_MEMBER_NOT_MODIFIED',
    LOCK_DISABLED: 'ROLLBACK_LOCK_DISABLED',
    LOCK_UNAVAILABLE: 'ROLLBACK_LOCK_UNAVAILABLE',
    LOCK_BUSY: 'ROLLBACK_LOCK_BUSY',
    LOCK_FENCE: 'ROLLBACK_LOCK_FENCE',
    DESTINATION_RETRIEVE_FAILED: 'ROLLBACK_DESTINATION_RETRIEVE_FAILED',
    DRIFT_DETECTED: 'ROLLBACK_DRIFT_DETECTED',
    WORKSPACE_FAILED: 'ROLLBACK_WORKSPACE_FAILED',
    PACKAGE_FAILED: 'ROLLBACK_PACKAGE_FAILED',
    CHECK_ONLY_FAILED: 'ROLLBACK_CHECK_ONLY_FAILED',
    EXECUTION_FAILED: 'ROLLBACK_EXECUTION_FAILED',
    ALREADY_IN_PROGRESS: 'ROLLBACK_ALREADY_IN_PROGRESS',
    ALREADY_COMPLETED: 'ROLLBACK_ALREADY_COMPLETED',
    RESULT_UNKNOWN: 'ROLLBACK_RESULT_UNKNOWN',
    RESULT_PERSISTENCE_UNKNOWN: 'ROLLBACK_RESULT_PERSISTENCE_UNKNOWN',
    OPERATION_STORE_UNAVAILABLE: 'ROLLBACK_OPERATION_STORE_UNAVAILABLE',
    SCOPE_AMBIGUOUS: 'ROLLBACK_OPERATION_SCOPE_AMBIGUOUS',
    SCOPE_BUSY: 'ROLLBACK_OPERATION_SCOPE_BUSY',
    AUTHORIZATION_DENIED: 'ROLLBACK_AUTHORIZATION_DENIED',
    AUTHORIZATION_UNAVAILABLE: 'ROLLBACK_AUTHORIZATION_UNAVAILABLE'
});

class RollbackBlockedError extends Error {
    constructor(code, message, details = {}) {
        super(message);
        this.name = 'RollbackBlockedError';
        this.code = code;
        this.details = details;
    }
}

module.exports = {
    ROLLBACK_CODE,
    RollbackBlockedError
};
